import type { APIRoute } from "astro";

// Alias for crawlers/tools that request /sitemap.xml by convention.
// Mirrors the sitemap index generated by @astrojs/sitemap.
export const GET: APIRoute = ({ site }) => {
  const origin = (site ?? new URL("https://karthickv.dev")).origin;
  const body = `<?xml version="1.0" encoding="UTF-8"?><sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><sitemap><loc>${origin}/sitemap-0.xml</loc></sitemap></sitemapindex>`;
  return new Response(body, { headers: { "Content-Type": "application/xml" } });
};
